# Generated by Django 5.2.1 on 2025-05-21 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=100)),
                ('estado', models.CharField(choices=[('Operativo', 'Operativo'), ('Mantenimiento', 'Mantenimiento'), ('No Operativo', 'No Operativo'), ('Otro', 'Otro')], max_length=100)),
                ('comentarios', models.TextField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.activoubicacion')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
            },
        ),
    ]
